namespace: tfc-agent
Secret:
  tfcToken: "placeholder-for-tfc-token"
agent:
  image: hashicorp/tfc-agent
  tag: 1.23
  logLevel: info
  tfcAddress: "https://app.terraform.io" # TFC server address
scriptConfigHash: ""
policyConfigHash": ""

# Deployment configuration
deployment:
  fsGroup: 0 # set it based on your k8s cluster, 0 for local development
  fsUser: 0 # set it based on your k8s cluster, 0 for local development
  replicaCount: 1
  resources:
    requests:
      cpu: 1000m
      memory: 3000Mi
    limits:
      cpu: 2000m
      memory: 6000Mi
  usePV: true # Set to true if using Persistent Volumes for plugins cache persistency when agent restarts
  # storageClassName: "agent-disk-essd" # "agent-disk-essd" for production
  # storageSize: "20Gi"
  storageClassName: "hostpath" # use "hostpath" for local development
  storageSize: "5Gi"
