#!/bin/sh
set -e
echo "===agent pre plan hook==="
echo "Workspace: "${TFC_WORKSPACE_NAME:-}
echo "RunID: "${TFC_RUN_ID:-}
# monnorepo cleanup unrelaeted folders except infrastructure
TARGET_RUN_DIR=/cache/data/component/terraform/runs/"$TFC_RUN_ID"
CONDITION_DIR=$(find $TARGET_RUN_DIR -type d -path "*/config/infrastructure/dev" 2>/dev/null | head -n 1)
if [ -n "$CONDITION_DIR" ] && [ -d "$CONDITION_DIR" ]; then
    TARGET_CONFIG_DIR="$TARGET_RUN_DIR/config"
    echo "Locate monorepo, will clean up other folders except infrastructure."
    cd "$TARGET_CONFIG_DIR"
    echo "Config Size before clean up:"
    du -sh .
    find . -mindepth 1 -maxdepth 1 ! -name "infrastructure" -exec rm -rf {} +
    echo "Config Size after clean up:"
    du -sh .
else
    echo "Not found monnorepo, skipping cleanup."
fi
